github_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: EIKVVTV-AH19983
      user: AIRBYTE_USER
      password: ""
      role: AIRBYTE_ROLE
      warehouse: AIRBYTE_WH
      database: GITHUB
      schema: STAGING
      threads: 4
      client_session_keep_alive: false